<a href="https://colab.research.google.com/github/ashokteja123/Machine-Learning/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LOGISTIC** **REGRESSION**

Logistic Regression is a classification algorithm used to predict binary or multi-class outcomes. It estimates the probability of an instance belonging to a particular class using the sigmoid function.

P(Y=1∣X)=
1+e
−(b
0
​
 +b
1
​
 X
1
​
 +b
2
​
 X
2
​
 +...+b
n
​
 X
n
​
 )

1
​

where:

𝑃
(
𝑌
=
1
∣
𝑋
)
P(Y=1∣X) is the probability that
𝑌
=
1
Y=1.
𝑏
0
,
𝑏
1
,
.
.
.
,
𝑏
𝑛
b
0
​
 ,b
1
​
 ,...,b
n
​
  are the model parameters (weights).
𝑋
1
,
𝑋
2
,
.
.
.
,
𝑋
𝑛
X
1
​
 ,X
2
​
 ,...,X
n
​
  are the input features.
If
𝑃
(
𝑌
=
1
∣
𝑋
)
>
0.5
P(Y=1∣X)>0.5, we predict class 1, otherwise class 0.


In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Sample dataset (features: X, target: Y)
data = {
    'X1': [2, 3, 5, 7, 8, 10, 12, 14, 15, 18],
    'X2': [1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
    'Y':  [0, 0, 0, 0, 1, 1, 1, 1, 1, 1]
}
df = pd.DataFrame(data)

# Independent variables (features) and dependent variable (target)
X = df[['X1', 'X2']]
Y = df['Y']

# Split dataset into training and testing sets (80%-20%)
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Train the Logistic Regression model
model = LogisticRegression()
model.fit(X_train, Y_train)

# Predict values
Y_pred = model.predict(X_test)

# Evaluate performance
print("Accuracy:", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Classification Report:\n", classification_report(Y_test, Y_pred))


Accuracy: 1.0
Confusion Matrix:
 [[1 0]
 [0 1]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



***Multi-Class Classification (One-vs-Rest)***

In [2]:
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler

# Load Iris dataset (3 classes)
iris = load_iris()
X = iris.data
Y = iris.target

# Normalize data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Train logistic regression
model = LogisticRegression(multi_class='ovr', solver='lbfgs')
model.fit(X_train, Y_train)

# Predict
Y_pred = model.predict(X_test)

# Accuracy
print("Accuracy:", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Classification Report:\n", classification_report(Y_test, Y_pred))


Accuracy: 0.9666666666666667
Confusion Matrix:
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
